### ISSUE TITLE
Set project based on URL when browsing GitHub, Waffle.io, CircleCi, etc

### ISSUE THREAD

**Issue by rummik** [wakatime/browser-wakatime#47]
Sites like GitHub, BitBucket, Travis-CI, ~Waffle.io~, and CircleCI, can contain the project name in the URL.  It would be nice to be able to use that info without exposing the full URL to the WakaTime API

**Comment by Eeems** [comment]
You can handle this via [custom rules](https://wakatime.com/settings/rules). It would be nice if the addon had some more powerful ways of determining what project things should go to.

**Comment by rummik** [comment]
Custom rules require exposing full URLs to the API, which could be considered a major security risk if the URLs contain session or personal information

**Comment by alanhamlett** [comment]
We could add the ability to call custom handlers to [WakaTimeCore.sendHeartbeat](https://github.com/wakatime/chrome-wakatime/blob/afc10fb7c4226a74d4a5a17fddb6449b53a21f92/assets/js/core/WakaTimeCore.js#L185).

Check if custom handler exists for given domain. If one exists, let that custom handler create the heartbeat payload data. Otherwise, use the default project and other heartbeat payload data.

Once custom handlers are working we can start adding custom handlers for any cloud IDE or websites we use.

**Comment by alanhamlett** [comment]
For Mac, we're building this now into the desktop app. If anyone has a url they want supported please common on https://github.com/wakatime/macos-wakatime/issues/227.
