### ISSUE TITLE
Problem using plugin in Brave Browser

### ISSUE THREAD

**Issue by karladler** [wakatime/browser-wakatime#86]
Maybe it's me or maybe its the app. I added several sites to the whitelist using the schema `https://subdmonain.domain.tld` and each on one line. But when I visit the sites the plugin icon seems to be disabled and states on hover "this URL is not on your whitelist".

Is it the config or is there an issue with the plugin?

If it helps: I use the recent stable version of the Brave Browser.

**Comment by karladler** [comment]
Tested it in chrome, works fine. It seems that in Brave Browser the login state is not detected. Probably there is some privacy setting to blame, just can't find which ...

**Comment by fcoclavero** [comment]
I can confirm the same issue. The blacklist isn't working in Brave either.

**Comment by CarbonCollins** [comment]
I can confirm I also had this issue, however after looking through my settings I had my cookies set to "only block cross-site" and once I changed it to "Allow all cookies" it seemed to start reporting back to wakatime.

It still said I was "signed in as [blank]" though...

I've previously had issues when accessing firebase apps because of the auth cookies being considered cross-site so as a stab in the dark I thought I would give it a try.

In regards to the white/black list not working, I had the extension running in developer mode with the console output and seemed to work. It was printing out messages like the following:
```
chrome://newtab/ is not on a whitelist.
events.js:413 recording a heartbeat - tab updated
events.js:301 {"entity":"https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events","type":"url","time":"1592218390","project":"<<LAST_PROJECT>>","is_debugging":false,"plugin":"chrome-wakatime/1.0.2"}
events.js:413 recording a heartbeat - tab updated
```
I have "https://developer.mozilla.org" on the whitelist and they were appearing correctly in my dashboard.

I hope this is of any help in solving this issue :)

**Comment by douglasjam** [comment]
same here, have whitelisted many domains that used to work on chrome but not on brave

`*.atlassian.net
*.aws.amazon.com
*.datadoghq.com
localhost`

**Comment by llinfeng** [comment]
I see the same type of failure with Vivaldi, for `localhost` alone.

**Comment by gkobeaga** [comment]
The following worked for me:

1. Enable cookies for **wakatime**.
   Open `brave://settings/cookies`, go to `Sites that can always use cookies` and add `[*.]wakatime.com`.
2. Whitelist the sites
```
https://subdmonain.domain.tld   # Works
https://*.domain.tld            # Does not work
*.domain.tld                    # Does not work
```
If you find that it does not report the activity of a "whitelisted" site, open `brave://extensions/` and in the wakatime extension card click on ` background page`. In the devtools console,  you will see `https://other.domain.tld is not on a whitelist`, add this url to your whitelist.

Note: As far as I've seen, there is no need to enable the cookies for the whitelisted sites, you can set them to "Cookies Blocked" in the Brave shield.

**Comment by jvelezpo** [comment]
Hello @karladler There is a new version of the extension v3, the issues reported above should be addressed now
Can you please confirm
